# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Naumen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Gloss'
  pod 'SnapKit'

  # Pods for Naumen

  target 'NaumenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaumenUITests' do
    # Pods for testing
  end

end
